import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'zh' | 'en' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'seo.title': 'INNEWTOLEA 因纽特莱 | 女性内在美养护品牌 - 胶原蛋白美肌营养',
    'seo.description': 'INNEWTOLEA因纽特莱，专注女性内在美养护。生命之花葡萄籽胶原胶囊，融合深海胶原肽、葡萄籽精华与多维营养，由内焕发自然光彩。温柔呵护，让美丽成为一种日常仪式。',
    'seo.keywords': 'INNEWTOLEA,因纽特莱,胶原蛋白,女性美容,内在美,葡萄籽精华,美肌营养,抗氧化,女性保健,美容保健品',
    'nav.home': '首页',
    'nav.values': '价值观',
    'nav.brandCulture': '品牌文化',
    'nav.about': '关于',
    'nav.contact': '联系',
    'nav.ritual': '产品',
    'nav.products': '产品',
    'brand.name': '因纽特莱',
    'hero.subtitle': '亲爱的你，无论你是否为我们客户',
    'hero.title.1': '我们都认为，你永远是',
    'hero.title.2': '世界上最美的女孩',
    'hero.desc': '这不是一句广告',
    'hero.desc.2': '这是我们创立品牌时，最初的心愿',
    'hero.desc.3': '希望你永远做最美丽的自己',
    'hero.scroll': '向下滚动',
    'about.label': '品牌文化',
    'about.title': '因纽特莱',
    'about.p1': '我们相信，美丽不应是负担',
    'about.p1.2': '而是一种温柔的日常仪式',
    'about.p2': 'INNEWTOLEA 诞生于一个简单的愿望：',
    'about.p2.2': '让每一位女性，都能以更轻松、更温柔、更可持续的方式，',
    'about.p2.3': '在忙碌的生活中，依然能够好好爱自己。',
    'about.p3': '我们不许诺瞬间改变，因为值得的美，都需要时间悄悄发芽',
    'about.p3.2': '我们相信小习惯的力量',
    'about.p3.3': '相信每一个微小的坚持，都在悄悄改变着什么',
    'about.quote': '"请爱上自己，温柔的呵护自己。"',
    'values.label': '我们的价值观',
    'values.title': '我们所相信的',
    'value.1.title': '温柔是力量',
    'value.1.en': 'Gentleness is Strength',
    'value.1.desc': '真正的强大，从不需要声嘶力竭。温柔地对待自己，是最深沉的勇气。',
    'value.2.title': '美是一种自由',
    'value.2.en': 'Beauty is Freedom',
    'value.2.desc': '美没有标准答案。你的独特，就是你最珍贵的风景。',
    'value.3.title': '坚持是最浪漫的事',
    'value.3.en': 'Persistence is Romance',
    'value.3.desc': '它像心跳一样安静，却悄悄把人带向光里。',
    'value.4.title': '小习惯值得被珍惜',
    'value.4.en': 'Small Rituals Matter',
    'value.4.desc': '小小的坚持，是你悄悄为自己点亮的光。',
    'value.5.title': '你值得更好的仪式感',
    'value.5.en': 'You Deserve Rituals',
    'value.5.desc': '生活的美好，在于那些认真对待自己的时刻。',
    'value.6.title': '爱自己是一生的功课',
    'value.6.en': 'Self-love is Lifelong',
    'value.6.desc': '不必急于完美，慢慢来，你正在成为最好的自己。',
    'women.label': '致你',
    'women.title': '致 每一个正在阅读这段文字的你',
    'women.p1': '你不是为了取悦世界而存在！',
    'women.p1.2': '请让太阳围绕而你发光。',
    'women.p2.1': '有些光来自温柔，',
    'women.p2.2': '有些光来自坚持，',
    'women.p2.3': '更多时候，它藏在那些被忽略的小日常里。',
    'women.p3.1': '你，是生命最真实的纹理；',
    'women.p3.2': '而脆弱，也是被允许的美。',
    'women.p4': '愿你，在拥抱世界中被待以温柔，',
    'women.p4.2': '也愿你，对待自己温柔以待。',
    'ritual.label': 'BEAUTY FROM WITHIN',
    'ritual.title': '明星产品',
    'product.name': '生命之花',
    'product.name.en': 'Flower of Life',
    'product.desc': '美好的改变，从每天的一颗温柔开始。',
    'ingredient.core.label': '核心有效成分',
    'ingredient.core.sublabel': 'Per Capsule / 每粒',
    'core.collagen': '胶原蛋白肽',
    'core.collagen.dose': '500 mg',
    'core.collagen.desc': '深海胶原肽，轻盈易吸收，帮助补充肌肤所需的"底层原料"，焕活柔嫩与弹性。',
    'core.grape': '葡萄籽提取物',
    'core.grape.dose': '40 mg（标准化 OPC）',
    'core.grape.desc': '自然界顶级抗氧化因子之一，温和守护年轻光彩，减轻日常自由基压力。',
    'ingredient.antioxidant.label': '双重抗氧组合',
    'ingredient.antioxidant.sublabel': '让光泽更持久',
    'vit.c': '维生素 C',
    'vit.c.dose': '100 mg',
    'vit.c.desc': '透亮肌肤、抗氧化基础营养，并支持胶原蛋白自然合成。',
    'vit.e': '维生素 E',
    'vit.e.dose': '10 mg α-TE',
    'vit.e.desc': '经典脂溶性抗氧化剂，与 VC 形成协同保护屏障，柔和抵御氧化。',
    'vit.beta': 'β-胡萝卜素',
    'vit.beta.dose': '500 μg RE',
    'vit.beta.desc': '更温和的维 A 形式，从内为肌肤与双眸带来自然光泽。',
    'ingredient.vitb.label': '维生素 B 族',
    'ingredient.vitb.sublabel': '点亮能量与元气',
    'vit.b2': '维生素 B2',
    'vit.b2.dose': '1.0 mg',
    'vit.b2.desc': '参与能量代谢，维持皮肤与黏膜健康。',
    'vit.b6': '维生素 B6',
    'vit.b6.dose': '1.0 mg',
    'vit.b6.desc': '支持蛋白质代谢，让身体更有效利用胶原。',
    'vit.biotin': '生物素',
    'vit.biotin.dose': '80 μg',
    'vit.biotin.desc': '女生必备的小成分，有助维持皮肤、头发与指甲的健康状态。',
    'ingredient.sunshine.label': '来自阳光的底气',
    'vit.d3': '维生素 D3',
    'vit.d3.dose': '10 μg（400 IU）',
    'vit.d3.desc': '补充"阳光营养"，为肌肤与身体基础代谢提供支持。',
    'ingredient.mineral.label': '矿物元素',
    'ingredient.mineral.sublabel': '恢复肌肤平衡的微量矿物力量',
    'mineral.zinc': '锌',
    'mineral.zinc.dose': '7 mg',
    'mineral.zinc.desc': '参与皮肤修护、免疫维持，使女生维持更稳定的状态。',
    'mineral.selenium': '硒',
    'mineral.selenium.dose': '30 μg',
    'mineral.selenium.desc': '人体必需抗氧化矿物，与葡萄籽 & 维生素 E 协同守护年轻。',
    'product.footer': '每一种成分的相遇，都是自然与科学的温柔对话',
    'product.footer.2': '轻盈一颗，美丽日常',
    'footer.wish': '愿你永远温柔，永远被温柔以待',
    // Brand Culture Page
    'brandCulture.hero.title': '因纽特莱',
    'brandCulture.hero.subtitle': '我们相信，美丽不应是负担',
    'brandCulture.hero.subtitle2': '而是一种温柔的日常仪式',
    'brandContent.intro': 'INNEWTOLEA 诞生于一个简单的愿望：',
    'brandContent.intro2': '让每一位女性，都能以更轻松、更温柔、更可持续的方式，',
    'brandContent.intro3': '在忙碌的生活中，依然能够好好爱自己。',
    'brandContent.p1': '我们不追求立竿见影的速效',
    'brandContent.p1_2': '我们相信小习惯的力量',
    'brandContent.p1_3': '相信每一个微小的坚持，都在悄悄改变着什么',
    'brandContent.quote': '"请爱上自己，温柔的呵护自己。"',
    // Contact Page
    'contact.hero.title': '联系我们',
    'contact.hero.subtitle': '期待与您的相遇',
    'contact.info.title': '联系方式',
    'contact.info.address': '公司地址',
    'contact.info.address.value': '浙江省杭州市西湖区文三路 90 号',
    'contact.info.phone': '联系电话',
    'contact.info.phone.value': '+86 571-8888-9999',
    'contact.info.email': '电子邮箱',
    'contact.info.email.value': 'hello@innewtolea.com',
    'contact.info.wechat': '微信客服',
    'contact.info.wechat.value': 'INNEWTOLEA_Service',
    'contact.info.hours': '工作时间',
    'contact.info.hours.value': '周一至周五 9:00-18:00',
    'contact.message.title': '留言咨询',
    'contact.message.desc': '如有任何问题或建议，欢迎随时与我们联系',
    'contact.form.name': '姓名',
    'contact.form.email': '邮箱',
    'contact.form.subject': '主题',
    'contact.form.message': '留言内容',
    'contact.form.submit': '发送消息',
    'contact.form.sending': '发送中...',
    'contact.form.success': '发送成功，我们会尽快回复您',
    'contact.map.title': '找到我们',
    // About Page
    'aboutPage.hero.title': 'INNEWTOLEA',
    'aboutPage.hero.subtitle': '因纽特莱',
    'aboutPage.hero.tagline': '进入一段焕新生命的旅程',
    'aboutPage.hero.tagline.en': 'A journey to a renewed, better you',
    'aboutPage.naming.title': '品牌命名寓意',
    'aboutPage.naming.intro': 'INNEWTOLEA 由四个具有象征意义的片段组成：',
    'aboutPage.naming.in.title': 'IN',
    'aboutPage.naming.in.meaning': '进入、由内而生的改变',
    'aboutPage.naming.in.desc': '代表健康从外表开始，但真正的力量源自内在。我们专注身体"内在循环"的改善，用营养支持最根本的改变。',
    'aboutPage.naming.new.title': 'NEW',
    'aboutPage.naming.new.meaning': '新的、更新的、焕新的希望',
    'aboutPage.naming.new.desc': '象征每天的重新开始、重新建立习惯、重新获得能量。也是品牌对用户的承诺："每天一点点，你会发现全新的自己。"',
    'aboutPage.naming.to.title': 'TO',
    'aboutPage.naming.to.meaning': '通往、过程、路径',
    'aboutPage.naming.to.desc': '健康不是一蹴而就，而是一段持续向前的旅程。TO 代表一条让人能够坚持、不造成负担、却真正有效的健康路径。',
    'aboutPage.naming.lea.title': 'LEA',
    'aboutPage.naming.lea.meaning': '生命、生长、活力',
    'aboutPage.naming.lea.desc': '源于柔和音节，象征生命的轻盈、生机与柔韧。让品牌整体更具国际感、美感与生命气息。',
    'aboutPage.philosophy.title': '品牌理念',
    'aboutPage.philosophy.core': '从内而外，走向更好的自己',
    'aboutPage.philosophy.intro': 'INNEWTOLEA 因纽特莱的名字来源于对健康本质的理解：健康不是某一刻的选择，而是一段从内出发、持续更新、朝向更好的生命状态的过程。',
    'aboutPage.philosophy.commitment.title': '我们的承诺',
    'aboutPage.philosophy.commitment.1': '轻奢但不昂贵的体验',
    'aboutPage.philosophy.commitment.2': '科学而不过度营销的配方',
    'aboutPage.philosophy.commitment.3': '人人都能坚持的营养方式',
    'aboutPage.philosophy.commitment.4': '美观、国际化、令人愉悦的产品美学',
    'aboutPage.philosophy.closing': '让每个人，都能以可负担、可坚持的方式，踏上一段属于自己的 INNEWTOLEA 生命焕新旅程。',
    'aboutPage.back': '返回首页',
  },
  en: {
    'seo.title': 'INNEWTOLEA | Women\'s Inner Beauty & Collagen Skincare Nutrition',
    'seo.description': 'INNEWTOLEA - Nurturing women\'s inner beauty. Flower of Life Grape Seed Collagen Capsules combine deep-sea collagen peptides, grape seed extract & multi-vitamins for natural radiance from within. Gentle care, making beauty a daily ritual.',
    'seo.keywords': 'INNEWTOLEA,collagen peptides,women beauty,inner beauty,grape seed extract,skincare nutrition,antioxidant,beauty supplements,collagen capsules',
    'nav.home': 'Home',
    'nav.values': 'Values',
    'nav.brandCulture': 'Brand Culture',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.ritual': 'Product',
    'nav.products': 'Products',
    'brand.name': 'INNEWTOLEA',
    'hero.subtitle': 'Dear you, whether you are our customer or not',
    'hero.title.1': 'We all believe you are always',
    'hero.title.2': 'The most beautiful girl in the world',
    'hero.desc': 'This is not an advertisement',
    'hero.desc.2': 'This is the original wish when we founded this brand',
    'hero.desc.3': 'We hope you will always be the most beautiful version of yourself',
    'hero.scroll': 'Scroll',
    'about.label': 'ABOUT INNEWTOLEA',
    'about.title': 'INNEWTOLEA',
    'about.p1': 'We believe beauty should not be a burden',
    'about.p1.2': 'But a gentle daily ritual',
    'about.p2': 'INNEWTOLEA was born from a simple wish:',
    'about.p2.2': 'To help every woman love herself',
    'about.p2.3': 'in an easier, gentler, more sustainable way, even in a busy life.',
    'about.p3': 'We don\'t promise instant change, because beauty worth having needs time to quietly blossom',
    'about.p3.2': 'We believe in the power of small habits',
    'about.p3.3': 'Every tiny persistence is quietly changing something',
    'about.quote': '"Please fall in love with yourself, and care for yourself tenderly."',
    'values.label': 'OUR VALUES',
    'values.title': 'What We Believe',
    'value.1.title': 'Gentleness is Strength',
    'value.1.en': 'Gentleness is Strength',
    'value.1.desc': 'True strength never needs to be loud. Treating yourself gently is the deepest courage.',
    'value.2.title': 'Beauty is Freedom',
    'value.2.en': 'Beauty is Freedom',
    'value.2.desc': 'Beauty has no standard answer. Your uniqueness is your most precious landscape.',
    'value.3.title': 'Persistence is Romance',
    'value.3.en': 'Persistence is Romance',
    'value.3.desc': 'It is as quiet as a heartbeat, yet gently leads you toward the light.',
    'value.4.title': 'Small Rituals Matter',
    'value.4.en': 'Small Rituals Matter',
    'value.4.desc': 'Small persistence is the light you quietly kindle for yourself.',
    'value.5.title': 'You Deserve Rituals',
    'value.5.en': 'You Deserve Rituals',
    'value.5.desc': 'The beauty of life lies in those moments when you take yourself seriously.',
    'value.6.title': 'Self-love is Lifelong',
    'value.6.en': 'Self-love is Lifelong',
    'value.6.desc': 'No need to rush for perfection. Take your time, you are becoming your best self.',
    'women.label': 'TO YOU',
    'women.title': 'To every one of you reading these words',
    'women.p1': 'You do not exist to please the world!',
    'women.p1.2': 'Let the sun orbit around you as you shine.',
    'women.p2.1': 'Some light comes from gentleness,',
    'women.p2.2': 'some from persistence,',
    'women.p2.3': 'and more often, it hides in the overlooked moments of daily life.',
    'women.p3.1': 'You are the truest texture of life;',
    'women.p3.2': 'and vulnerability is also a permitted beauty.',
    'women.p4': 'May you be treated with tenderness as you embrace the world,',
    'women.p4.2': 'and may you treat yourself with that same gentleness.',
    'ritual.label': 'BEAUTY FROM WITHIN',
    'ritual.title': 'Star Product',
    'product.name': 'Flower of Life',
    'product.name.en': 'Flower of Life',
    'product.desc': 'Beautiful changes begin with one gentle capsule each day.',
    'ingredient.core.label': 'CORE ACTIVE INGREDIENTS',
    'ingredient.core.sublabel': 'Per Capsule',
    'core.collagen': 'Collagen Peptides',
    'core.collagen.dose': '500 mg',
    'core.collagen.desc': 'Deep-sea collagen peptides, light and easily absorbed, helping replenish the "foundation" your skin needs for softness and elasticity.',
    'core.grape': 'Grape Seed Extract',
    'core.grape.dose': '40 mg (Standardized OPC)',
    'core.grape.desc': 'One of nature\'s top antioxidants, gently preserving youthful radiance and reducing daily free radical stress.',
    'ingredient.antioxidant.label': 'DUAL ANTIOXIDANT COMPLEX',
    'ingredient.antioxidant.sublabel': 'For lasting radiance',
    'vit.c': 'Vitamin C',
    'vit.c.dose': '100 mg',
    'vit.c.desc': 'Brightens skin, provides essential antioxidant nutrition, and supports natural collagen synthesis.',
    'vit.e': 'Vitamin E',
    'vit.e.dose': '10 mg α-TE',
    'vit.e.desc': 'Classic fat-soluble antioxidant, works synergistically with Vitamin C to create a protective barrier against oxidation.',
    'vit.beta': 'Beta-Carotene',
    'vit.beta.dose': '500 μg RE',
    'vit.beta.desc': 'A gentler form of Vitamin A, bringing natural radiance to skin and eyes from within.',
    'ingredient.vitb.label': 'B VITAMINS',
    'ingredient.vitb.sublabel': 'Energize and vitalize',
    'vit.b2': 'Vitamin B2',
    'vit.b2.dose': '1.0 mg',
    'vit.b2.desc': 'Participates in energy metabolism, maintaining healthy skin and mucous membranes.',
    'vit.b6': 'Vitamin B6',
    'vit.b6.dose': '1.0 mg',
    'vit.b6.desc': 'Supports protein metabolism, helping the body utilize collagen more effectively.',
    'vit.biotin': 'Biotin',
    'vit.biotin.dose': '80 μg',
    'vit.biotin.desc': 'An essential nutrient for women, helps maintain healthy skin, hair, and nails.',
    'ingredient.sunshine.label': 'SUNSHINE CONFIDENCE',
    'vit.d3': 'Vitamin D3',
    'vit.d3.dose': '10 μg (400 IU)',
    'vit.d3.desc': 'Supplements "sunshine nutrition", supporting skin health and basic body metabolism.',
    'ingredient.mineral.label': 'MINERAL ELEMENTS',
    'ingredient.mineral.sublabel': 'Trace minerals for skin balance',
    'mineral.zinc': 'Zinc',
    'mineral.zinc.dose': '7 mg',
    'mineral.zinc.desc': 'Participates in skin repair and immune maintenance, helping women maintain a more stable state.',
    'mineral.selenium': 'Selenium',
    'mineral.selenium.dose': '30 μg',
    'mineral.selenium.desc': 'Essential antioxidant mineral, works synergistically with grape seed & Vitamin E to preserve youth.',
    'product.footer': 'Every ingredient\'s encounter is a gentle dialogue between nature and science',
    'product.footer.2': 'One capsule, beautiful daily ritual',
    'footer.wish': 'May you always be gentle and be treated gently',
    // Brand Culture Page
    'brandCulture.hero.title': 'INNEWTOLEA',
    'brandCulture.hero.subtitle': 'We believe beauty should not be a burden',
    'brandCulture.hero.subtitle2': 'But a gentle daily ritual',
    'brandContent.intro': 'INNEWTOLEA was born from a simple wish:',
    'brandContent.intro2': 'To help every woman love herself',
    'brandContent.intro3': 'in an easier, gentler, more sustainable way, even in a busy life.',
    'brandContent.p1': 'We don\'t pursue instant results',
    'brandContent.p1_2': 'We believe in the power of small habits',
    'brandContent.p1_3': 'Every tiny persistence is quietly changing something',
    'brandContent.quote': '"Please fall in love with yourself, and care for yourself tenderly."',
    // Contact Page
    'contact.hero.title': 'Contact Us',
    'contact.hero.subtitle': 'We look forward to connecting with you',
    'contact.info.title': 'Contact Information',
    'contact.info.address': 'Address',
    'contact.info.address.value': 'No. 90 Wensan Road, Xihu District, Hangzhou, Zhejiang',
    'contact.info.phone': 'Phone',
    'contact.info.phone.value': '+86 571-8888-9999',
    'contact.info.email': 'Email',
    'contact.info.email.value': 'hello@innewtolea.com',
    'contact.info.wechat': 'WeChat',
    'contact.info.wechat.value': 'INNEWTOLEA_Service',
    'contact.info.hours': 'Business Hours',
    'contact.info.hours.value': 'Monday to Friday 9:00-18:00',
    'contact.message.title': 'Send us a message',
    'contact.message.desc': 'If you have any questions or suggestions, feel free to contact us',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully! We will get back to you soon',
    'contact.map.title': 'Find Us',
    // About Page
    'aboutPage.hero.title': 'INNEWTOLEA',
    'aboutPage.hero.subtitle': 'INNEWTOLEA',
    'aboutPage.hero.tagline': 'A journey to a renewed, better you',
    'aboutPage.hero.tagline.en': 'A journey to a renewed, better you',
    'aboutPage.naming.title': 'Brand Name Meaning',
    'aboutPage.naming.intro': 'INNEWTOLEA is composed of four symbolic fragments:',
    'aboutPage.naming.in.title': 'IN',
    'aboutPage.naming.in.meaning': 'Inner transformation',
    'aboutPage.naming.in.desc': 'Health starts from the outside, but true strength comes from within. We focus on improving the body\'s "inner cycle" with nutritional support for fundamental change.',
    'aboutPage.naming.new.title': 'NEW',
    'aboutPage.naming.new.meaning': 'New beginnings, renewal, hope',
    'aboutPage.naming.new.desc': 'Symbolizes daily fresh starts, rebuilding habits, regaining energy. Our promise to you: "Little by little, you\'ll discover a brand new you."',
    'aboutPage.naming.to.title': 'TO',
    'aboutPage.naming.to.meaning': 'Toward, journey, pathway',
    'aboutPage.naming.to.desc': 'Health isn\'t achieved overnight—it\'s a continuous journey forward. TO represents a sustainable, burden-free, yet truly effective path to wellness.',
    'aboutPage.naming.lea.title': 'LEA',
    'aboutPage.naming.lea.meaning': 'Life, growth, vitality',
    'aboutPage.naming.lea.desc': 'Derived from soft syllables, symbolizing life\'s lightness, vitality, and resilience. Giving the brand an international, aesthetic, and life-affirming presence.',
    'aboutPage.philosophy.title': 'Brand Philosophy',
    'aboutPage.philosophy.core': 'From within to without, toward a better you',
    'aboutPage.philosophy.intro': 'The name INNEWTOLEA comes from understanding the essence of health: it\'s not a single choice, but a journey from within, continuously renewing toward a better state of being.',
    'aboutPage.philosophy.commitment.title': 'Our Commitment',
    'aboutPage.philosophy.commitment.1': 'Affordable luxury experience',
    'aboutPage.philosophy.commitment.2': 'Science-based, not over-marketed formulas',
    'aboutPage.philosophy.commitment.3': 'Nutrition everyone can sustain',
    'aboutPage.philosophy.commitment.4': 'Beautiful, international, delightful product aesthetics',
    'aboutPage.philosophy.closing': 'Enabling everyone to embark on their own INNEWTOLEA journey of life renewal in an affordable, sustainable way.',
    'aboutPage.back': 'Back to Home',
  },
  ko: {
    'seo.title': 'INNEWTOLEA 인뉴톨레아 | 여성 이너뷰티 & 콜라겐 스킨케어 영양제',
    'seo.description': 'INNEWTOLEA 인뉴톨레아 - 여성의 내면의 아름다움을 가꿉니다. 생명의 꽃 포도씨 콜라겐 캡슐은 심해 콜라겐 펩타이드, 포도씨 추출물, 멀티비타민을 결합하여 내면에서 자연스러운 광채를 선사합니다.',
    'seo.keywords': 'INNEWTOLEA,인뉴톨레아,콜라겐,여성미용,이너뷰티,포도씨추출물,스킨케어영양,항산화,뷰티서플리먼트',
    'nav.home': '홈',
    'nav.values': '가치관',
    'nav.brandCulture': '브랜드 문화',
    'nav.about': '소개',
    'nav.contact': '연락처',
    'nav.ritual': '제품',
    'nav.products': '제품',
    'brand.name': '인뉴톨레아',
    'hero.subtitle': '사랑하는 당신, 저희 고객이든 아니든',
    'hero.title.1': '우리 모두는 믿습니다, 당신은 언제나',
    'hero.title.2': '세상에서 가장 아름다운 여자',
    'hero.desc': '이것은 광고가 아닙니다',
    'hero.desc.2': '이것은 브랜드를 설립할 때 처음 품었던 소망입니다',
    'hero.desc.3': '당신이 항상 가장 아름다운 자신이 되길 바랍니다',
    'hero.scroll': '스크롤',
    'about.label': '인뉴톨레아 소개',
    'about.title': '인뉴톨레아',
    'about.p1': '우리는 아름다움이 부담이 되어서는 안 된다고 믿습니다',
    'about.p1.2': '오히려 부드러운 일상의 의식이어야 합니다',
    'about.p2': 'INNEWTOLEA는 단순한 소망에서 탄생했습니다:',
    'about.p2.2': '모든 여성이 더 쉽고, 더 부드럽고, 더 지속 가능한 방법으로',
    'about.p2.3': '바쁜 삶 속에서도 자신을 사랑할 수 있도록.',
    'about.p3': '우리는 순간적인 변화를 약속하지 않습니다, 가치 있는 아름다움은 조용히 피어날 시간이 필요하기 때문입니다',
    'about.p3.2': '우리는 작은 습관의 힘을 믿습니다',
    'about.p3.3': '모든 작은 지속이 조용히 무언가를 바꾸고 있습니다',
    'about.quote': '"자신을 사랑하고, 부드럽게 보살펴 주세요."',
    'values.label': '우리의 가치관',
    'values.title': '우리가 믿는 것',
    'value.1.title': '부드러움은 힘이다',
    'value.1.en': 'Gentleness is Strength',
    'value.1.desc': '진정한 강함은 결코 소리 높일 필요가 없습니다. 자신을 부드럽게 대하는 것이 가장 깊은 용기입니다.',
    'value.2.title': '아름다움은 자유다',
    'value.2.en': 'Beauty is Freedom',
    'value.2.desc': '아름다움에는 정답이 없습니다. 당신의 독특함이 가장 소중한 풍경입니다.',
    'value.3.title': '지속은 가장 로맨틱한 일',
    'value.3.en': 'Persistence is Romance',
    'value.3.desc': '심장 박동처럼 조용하지만, 당신을 빛 속으로 이끌어 줍니다.',
    'value.4.title': '작은 습관도 소중히',
    'value.4.en': 'Small Rituals Matter',
    'value.4.desc': '작은 지속은 당신이 조용히 스스로를 위해 켜는 빛입니다.',
    'value.5.title': '당신은 의식을 누릴 자격이 있다',
    'value.5.en': 'You Deserve Rituals',
    'value.5.desc': '삶의 아름다움은 자신을 진지하게 대하는 순간에 있습니다.',
    'value.6.title': '자기 사랑은 평생의 과제',
    'value.6.en': 'Self-love is Lifelong',
    'value.6.desc': '완벽을 서두를 필요 없습니다. 천천히, 당신은 최고의 자신이 되어가고 있습니다.',
    'women.label': '당신에게',
    'women.title': '이 글을 읽고 있는 모든 당신에게',
    'women.p1': '당신은 세상을 기쁘게 하기 위해 존재하지 않습니다!',
    'women.p1.2': '태양이 당신을 중심으로 빛나게 하세요.',
    'women.p2.1': '어떤 빛은 부드러움에서,',
    'women.p2.2': '어떤 빛은 끈기에서,',
    'women.p2.3': '더 많은 경우, 그것은 간과된 일상 속에 숨어 있습니다.',
    'women.p3.1': '당신은 삶의 가장 진실한 결입니다;',
    'women.p3.2': '그리고 연약함도 허용된 아름다움입니다.',
    'women.p4': '세상을 품는 당신이 부드럽게 대해지길 바라며,',
    'women.p4.2': '그 온기로 자신을 대하길 바랍니다.',
    'ritual.label': 'BEAUTY FROM WITHIN',
    'ritual.title': '스타 제품',
    'product.name': '생명의 꽃',
    'product.name.en': 'Flower of Life',
    'product.desc': '아름다운 변화는 매일 한 알의 부드러움에서 시작됩니다.',
    'ingredient.core.label': '핵심 유효 성분',
    'ingredient.core.sublabel': '1캡슐당 함량',
    'core.collagen': '콜라겐 펩타이드',
    'core.collagen.dose': '500 mg',
    'core.collagen.desc': '심해 콜라겐 펩타이드, 가볍고 흡수가 쉬우며, 피부에 필요한 "기초 원료"를 보충하여 부드러움과 탄력을 되찾게 합니다.',
    'core.grape': '포도씨 추출물',
    'core.grape.dose': '40 mg (표준화 OPC)',
    'core.grape.desc': '자연계 최고의 항산화 성분 중 하나로, 젊은 광채를 부드럽게 지키고 일상의 활성산소 스트레스를 줄여줍니다.',
    'ingredient.antioxidant.label': '이중 항산화 조합',
    'ingredient.antioxidant.sublabel': '지속적인 광채를 위해',
    'vit.c': '비타민 C',
    'vit.c.dose': '100 mg',
    'vit.c.desc': '피부를 환하게 하고, 항산화 기본 영양을 제공하며, 자연스러운 콜라겐 합성을 지원합니다.',
    'vit.e': '비타민 E',
    'vit.e.dose': '10 mg α-TE',
    'vit.e.desc': '클래식한 지용성 항산화제로, 비타민 C와 함께 산화에 대한 보호 장벽을 형성합니다.',
    'vit.beta': '베타카로틴',
    'vit.beta.dose': '500 μg RE',
    'vit.beta.desc': '더 순한 형태의 비타민 A로, 피부와 눈에 자연스러운 광채를 선사합니다.',
    'ingredient.vitb.label': '비타민 B군',
    'ingredient.vitb.sublabel': '에너지와 활력 충전',
    'vit.b2': '비타민 B2',
    'vit.b2.dose': '1.0 mg',
    'vit.b2.desc': '에너지 대사에 참여하여 건강한 피부와 점막을 유지합니다.',
    'vit.b6': '비타민 B6',
    'vit.b6.dose': '1.0 mg',
    'vit.b6.desc': '단백질 대사를 지원하여 콜라겐을 더 효과적으로 활용하도록 돕습니다.',
    'vit.biotin': '비오틴',
    'vit.biotin.dose': '80 μg',
    'vit.biotin.desc': '여성에게 필수적인 영양소로, 건강한 피부, 모발, 손톱 유지를 돕습니다.',
    'ingredient.sunshine.label': '햇살의 자신감',
    'vit.d3': '비타민 D3',
    'vit.d3.dose': '10 μg (400 IU)',
    'vit.d3.desc': '"햇살 영양"을 보충하여 피부 건강과 기초 대사를 지원합니다.',
    'ingredient.mineral.label': '미네랄 원소',
    'ingredient.mineral.sublabel': '피부 균형을 위한 미량 미네랄',
    'mineral.zinc': '아연',
    'mineral.zinc.dose': '7 mg',
    'mineral.zinc.desc': '피부 회복과 면역 유지에 참여하여 더 안정적인 상태를 유지하도록 돕습니다.',
    'mineral.selenium': '셀레늄',
    'mineral.selenium.dose': '30 μg',
    'mineral.selenium.desc': '필수 항산화 미네랄로, 포도씨 & 비타민 E와 함께 젊음을 지킵니다.',
    'product.footer': '모든 성분의 만남은 자연과 과학의 부드러운 대화입니다',
    'product.footer.2': '가벼운 한 알, 아름다운 일상',
    'footer.wish': '언제나 부드럽고, 부드럽게 대해지길',
    // Brand Culture Page
    'brandCulture.hero.title': '인뉴톨레아',
    'brandCulture.hero.subtitle': '우리는 아름다움이 부담이 되어서는 안 된다고 믿습니다',
    'brandCulture.hero.subtitle2': '오히려 부드러운 일상의 의식이어야 합니다',
    'brandContent.intro': 'INNEWTOLEA는 단순한 소망에서 탄생했습니다:',
    'brandContent.intro2': '모든 여성이 더 쉽고, 더 부드럽고, 더 지속 가능한 방법으로',
    'brandContent.intro3': '바쁜 삶 속에서도 자신을 사랑할 수 있도록.',
    'brandContent.p1': '우리는 즉각적인 효과를 추구하지 않습니다',
    'brandContent.p1_2': '우리는 작은 습관의 힘을 믿습니다',
    'brandContent.p1_3': '모든 작은 지속이 조용히 무언가를 바꾸고 있습니다',
    'brandContent.quote': '"자신을 사랑하고, 부드럽게 보살펴 주세요."',
    // Contact Page
    'contact.hero.title': '연락처',
    'contact.hero.subtitle': '만나기를 기대합니다',
    'contact.info.title': '연락 정보',
    'contact.info.address': '주소',
    'contact.info.address.value': '저장성 항저우시 서호구 문산로 90호',
    'contact.info.phone': '전화',
    'contact.info.phone.value': '+86 571-8888-9999',
    'contact.info.email': '이메일',
    'contact.info.email.value': 'hello@innewtolea.com',
    'contact.info.wechat': '위챗',
    'contact.info.wechat.value': 'INNEWTOLEA_Service',
    'contact.info.hours': '업무 시간',
    'contact.info.hours.value': '월요일-금요일 9:00-18:00',
    'contact.message.title': '문의하기',
    'contact.message.desc': '질문이나 제안이 있으시면 언제든지 연락주세요',
    'contact.form.name': '이름',
    'contact.form.email': '이메일',
    'contact.form.subject': '제목',
    'contact.form.message': '메시지',
    'contact.form.submit': '메시지 보내기',
    'contact.form.sending': '전송 중...',
    'contact.form.success': '메시지가 성공적으로 전송되었습니다! 곧 연락드리겠습니다',
    'contact.map.title': '찾아오시는 길',
    // About Page
    'aboutPage.hero.title': 'INNEWTOLEA',
    'aboutPage.hero.subtitle': '인뉴톨레아',
    'aboutPage.hero.tagline': '새로운 삶의 여정으로',
    'aboutPage.hero.tagline.en': 'A journey to a renewed, better you',
    'aboutPage.naming.title': '브랜드 네이밍 의미',
    'aboutPage.naming.intro': 'INNEWTOLEA는 네 가지 상징적인 조각으로 구성됩니다:',
    'aboutPage.naming.in.title': 'IN',
    'aboutPage.naming.in.meaning': '내면의 변화',
    'aboutPage.naming.in.desc': '건강은 외면에서 시작되지만, 진정한 힘은 내면에서 옵니다. 우리는 근본적인 변화를 위한 영양 지원으로 신체의 "내부 순환" 개선에 집중합니다.',
    'aboutPage.naming.new.title': 'NEW',
    'aboutPage.naming.new.meaning': '새로운 시작, 갱신, 희망',
    'aboutPage.naming.new.desc': '매일의 새로운 시작, 습관 재건, 에너지 회복을 상징합니다. 당신에게 드리는 약속: "조금씩, 완전히 새로운 자신을 발견하게 될 것입니다."',
    'aboutPage.naming.to.title': 'TO',
    'aboutPage.naming.to.meaning': '향하여, 여정, 경로',
    'aboutPage.naming.to.desc': '건강은 하룻밤에 이루어지지 않습니다—지속적인 전진의 여정입니다. TO는 지속 가능하고, 부담 없으며, 진정으로 효과적인 웰니스 경로를 나타냅니다.',
    'aboutPage.naming.lea.title': 'LEA',
    'aboutPage.naming.lea.meaning': '생명, 성장, 활력',
    'aboutPage.naming.lea.desc': '부드러운 음절에서 유래하여 삶의 가벼움, 활력, 회복력을 상징합니다. 브랜드에 국제적이고 미학적이며 생명력 있는 존재감을 부여합니다.',
    'aboutPage.philosophy.title': '브랜드 철학',
    'aboutPage.philosophy.core': '내면에서 외면으로, 더 나은 자신을 향해',
    'aboutPage.philosophy.intro': 'INNEWTOLEA라는 이름은 건강의 본질에 대한 이해에서 비롯됩니다: 건강은 단일한 선택이 아니라, 내면에서 시작하여 지속적으로 갱신하며 더 나은 존재 상태를 향한 여정입니다.',
    'aboutPage.philosophy.commitment.title': '우리의 약속',
    'aboutPage.philosophy.commitment.1': '합리적인 럭셔리 경험',
    'aboutPage.philosophy.commitment.2': '과학 기반, 과대 마케팅 없는 포뮬러',
    'aboutPage.philosophy.commitment.3': '누구나 지속할 수 있는 영양',
    'aboutPage.philosophy.commitment.4': '아름답고 국제적이며 즐거운 제품 미학',
    'aboutPage.philosophy.closing': '모든 사람이 합리적이고 지속 가능한 방식으로 자신만의 INNEWTOLEA 생명 갱신 여정을 시작할 수 있도록 합니다.',
    'aboutPage.back': '홈으로 돌아가기',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
