import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'zh' | 'en' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'seo.title': 'INNEWTOLEA 因纽特莱 | 女性内在美养护品牌 - 胶原蛋白美肌营养',
    'seo.description': 'INNEWTOLEA因纽特莱，专注女性内在美养护。生命之花葡萄籽胶原胶囊，融合深海胶原肽、葡萄籽精华与多维营养，由内焕发自然光彩。温柔呵护，让美丽成为一种日常仪式。',
    'seo.keywords': 'INNEWTOLEA,因纽特莱,胶原蛋白,女性美容,内在美,葡萄籽精华,美肌营养,抗氧化,女性保健,美容保健品',
    'nav.about': '关于',
    'nav.values': '价值观',
    'nav.ritual': '产品',
    'brand.name': '因纽特莱',
    'hero.subtitle': '亲爱的你，无论你是否为我们的客户',
    'hero.title.1': '我们认为，你永远是',
    'hero.title.2': '世界上最美的女孩',
    'hero.desc': '这不是一句营销话术',
    'hero.desc.2': '这是我们创立品牌时，最初的心愿',
    'hero.scroll': '向下滚动',
    'about.label': '关于因纽特莱',
    'about.title': '因纽特莱',
    'about.p1': '我们相信，美丽不应是负担',
    'about.p1.2': '而是一种温柔的日常仪式',
    'about.p2': 'INNEWTOLEA 诞生于一个简单的愿望：',
    'about.p2.2': '让每一位女性，都能以更轻松、更温柔、更可持续的方式，',
    'about.p2.3': '在忙碌的生活中，依然能够好好爱自己。',
    'about.p3': '我们不追求立竿见影的速效',
    'about.p3.2': '我们相信小习惯的力量',
    'about.p3.3': '相信每一个微小的坚持，都在悄悄改变着什么',
    'about.quote': '"请爱上自己，温柔的呵护自己。"',
    'values.label': '我们的价值观',
    'values.title': '我们所相信的',
    'value.1.title': '温柔是力量',
    'value.1.en': 'Gentleness is Strength',
    'value.1.desc': '真正的强大，从不需要声嘶力竭。温柔地对待自己，是最深沉的勇气。',
    'value.2.title': '美是一种自由',
    'value.2.en': 'Beauty is Freedom',
    'value.2.desc': '美没有标准答案。你的独特，就是你最珍贵的风景。',
    'value.3.title': '坚持是最浪漫的事',
    'value.3.en': 'Persistence is Romance',
    'value.3.desc': '它像心跳一样安静，却悄悄把人带向光里。',
    'value.4.title': '小习惯值得被珍惜',
    'value.4.en': 'Small Rituals Matter',
    'value.4.desc': '小小的坚持，是你悄悄为自己点亮的光。',
    'value.5.title': '你值得更好的仪式感',
    'value.5.en': 'You Deserve Rituals',
    'value.5.desc': '生活的美好，在于那些认真对待自己的时刻。',
    'value.6.title': '爱自己是一生的功课',
    'value.6.en': 'Self-love is Lifelong',
    'value.6.desc': '不必急于完美，慢慢来，你正在成为最好的自己。',
    'women.label': '致你',
    'women.title': '致 每一个正在阅读这段文字的你',
    'women.p1': '你不是为了取悦世界而存在！',
    'women.p1.2': '请让太阳围绕而你发光。',
    'women.p2.1': '有些光来自温柔，',
    'women.p2.2': '有些光来自坚持，',
    'women.p2.3': '更多时候，它藏在那些被忽略的小日常里。',
    'women.p3.1': '你，是生命最真实的纹理；',
    'women.p3.2': '而脆弱，也是被允许的美。',
    'women.p4': '愿你，在拥抱世界中被待以温柔，',
    'women.p4.2': '也愿你，对待自己温柔以待。',
    'ritual.label': 'BEAUTY FROM WITHIN',
    'ritual.title': '明星产品',
    'product.name': '生命之花',
    'product.name.en': 'Flower of Life',
    'product.desc': '美好的改变，从每天的一颗温柔开始。',
    'ingredient.core.label': '核心有效成分',
    'ingredient.core.sublabel': 'Per Capsule / 每粒',
    'core.collagen': '胶原蛋白肽',
    'core.collagen.dose': '500 mg',
    'core.collagen.desc': '深海胶原肽，轻盈易吸收，帮助补充肌肤所需的"底层原料"，焕活柔嫩与弹性。',
    'core.grape': '葡萄籽提取物',
    'core.grape.dose': '40 mg（标准化 OPC）',
    'core.grape.desc': '自然界顶级抗氧化因子之一，温和守护年轻光彩，减轻日常自由基压力。',
    'ingredient.antioxidant.label': '双重抗氧组合',
    'ingredient.antioxidant.sublabel': '让光泽更持久',
    'vit.c': '维生素 C',
    'vit.c.dose': '100 mg',
    'vit.c.desc': '透亮肌肤、抗氧化基础营养，并支持胶原蛋白自然合成。',
    'vit.e': '维生素 E',
    'vit.e.dose': '10 mg α-TE',
    'vit.e.desc': '经典脂溶性抗氧化剂，与 VC 形成协同保护屏障，柔和抵御氧化。',
    'vit.beta': 'β-胡萝卜素',
    'vit.beta.dose': '500 μg RE',
    'vit.beta.desc': '更温和的维 A 形式，从内为肌肤与双眸带来自然光泽。',
    'ingredient.vitb.label': '维生素 B 族',
    'ingredient.vitb.sublabel': '点亮能量与元气',
    'vit.b2': '维生素 B2',
    'vit.b2.dose': '1.0 mg',
    'vit.b2.desc': '参与能量代谢，维持皮肤与黏膜健康。',
    'vit.b6': '维生素 B6',
    'vit.b6.dose': '1.0 mg',
    'vit.b6.desc': '支持蛋白质代谢，让身体更有效利用胶原。',
    'vit.biotin': '生物素',
    'vit.biotin.dose': '80 μg',
    'vit.biotin.desc': '女生必备的小成分，有助维持皮肤、头发与指甲的健康状态。',
    'ingredient.sunshine.label': '来自阳光的底气',
    'vit.d3': '维生素 D3',
    'vit.d3.dose': '10 μg（400 IU）',
    'vit.d3.desc': '补充"阳光营养"，为肌肤与身体基础代谢提供支持。',
    'ingredient.mineral.label': '矿物元素',
    'ingredient.mineral.sublabel': '恢复肌肤平衡的微量矿物力量',
    'mineral.zinc': '锌',
    'mineral.zinc.dose': '7 mg',
    'mineral.zinc.desc': '参与皮肤修护、免疫维持，使女生维持更稳定的状态。',
    'mineral.selenium': '硒',
    'mineral.selenium.dose': '30 μg',
    'mineral.selenium.desc': '人体必需抗氧化矿物，与葡萄籽 & 维生素 E 协同守护年轻。',
    'product.footer': '每一种成分的相遇，都是自然与科学的温柔对话',
    'product.footer.2': '轻盈一颗，美丽日常',
    'footer.wish': '愿你永远温柔，永远被温柔以待',
  },
  en: {
    'seo.title': 'INNEWTOLEA | Women\'s Inner Beauty & Collagen Skincare Nutrition',
    'seo.description': 'INNEWTOLEA - Nurturing women\'s inner beauty. Flower of Life Grape Seed Collagen Capsules combine deep-sea collagen peptides, grape seed extract & multi-vitamins for natural radiance from within. Gentle care, making beauty a daily ritual.',
    'seo.keywords': 'INNEWTOLEA,collagen peptides,women beauty,inner beauty,grape seed extract,skincare nutrition,antioxidant,beauty supplements,collagen capsules',
    'nav.about': 'About',
    'nav.values': 'Values',
    'nav.ritual': 'Product',
    'brand.name': 'INNEWTOLEA',
    'hero.subtitle': 'Dear you, whether you are our customer or not',
    'hero.title.1': 'We believe you are always',
    'hero.title.2': 'The most beautiful girl in the world',
    'hero.desc': 'This is not a marketing slogan',
    'hero.desc.2': 'This is the original wish when we founded this brand',
    'hero.scroll': 'Scroll',
    'about.label': 'ABOUT INNEWTOLEA',
    'about.title': 'INNEWTOLEA',
    'about.p1': 'We believe beauty should not be a burden',
    'about.p1.2': 'But a gentle daily ritual',
    'about.p2': 'INNEWTOLEA was born from a simple wish:',
    'about.p2.2': 'To help every woman love herself',
    'about.p2.3': 'in an easier, gentler, more sustainable way, even in a busy life.',
    'about.p3': 'We don\'t pursue instant results',
    'about.p3.2': 'We believe in the power of small habits',
    'about.p3.3': 'Every tiny persistence is quietly changing something',
    'about.quote': '"Please fall in love with yourself, and care for yourself tenderly."',
    'values.label': 'OUR VALUES',
    'values.title': 'What We Believe',
    'value.1.title': 'Gentleness is Strength',
    'value.1.en': 'Gentleness is Strength',
    'value.1.desc': 'True strength never needs to be loud. Treating yourself gently is the deepest courage.',
    'value.2.title': 'Beauty is Freedom',
    'value.2.en': 'Beauty is Freedom',
    'value.2.desc': 'Beauty has no standard answer. Your uniqueness is your most precious landscape.',
    'value.3.title': 'Persistence is Romance',
    'value.3.en': 'Persistence is Romance',
    'value.3.desc': 'It is as quiet as a heartbeat, yet gently leads you toward the light.',
    'value.4.title': 'Small Rituals Matter',
    'value.4.en': 'Small Rituals Matter',
    'value.4.desc': 'Small persistence is the light you quietly kindle for yourself.',
    'value.5.title': 'You Deserve Rituals',
    'value.5.en': 'You Deserve Rituals',
    'value.5.desc': 'The beauty of life lies in those moments when you take yourself seriously.',
    'value.6.title': 'Self-love is Lifelong',
    'value.6.en': 'Self-love is Lifelong',
    'value.6.desc': 'No need to rush for perfection. Take your time, you are becoming your best self.',
    'women.label': 'TO YOU',
    'women.title': 'To every one of you reading these words',
    'women.p1': 'You do not exist to please the world!',
    'women.p1.2': 'Let the sun orbit around you as you shine.',
    'women.p2.1': 'Some light comes from gentleness,',
    'women.p2.2': 'some from persistence,',
    'women.p2.3': 'and more often, it hides in the overlooked moments of daily life.',
    'women.p3.1': 'You are the truest texture of life;',
    'women.p3.2': 'and vulnerability is also a permitted beauty.',
    'women.p4': 'May you be treated with tenderness as you embrace the world,',
    'women.p4.2': 'and may you treat yourself with that same gentleness.',
    'ritual.label': 'BEAUTY FROM WITHIN',
    'ritual.title': 'Star Product',
    'product.name': 'Flower of Life',
    'product.name.en': 'Flower of Life',
    'product.desc': 'Beautiful changes begin with one gentle capsule each day.',
    'ingredient.core.label': 'CORE ACTIVE INGREDIENTS',
    'ingredient.core.sublabel': 'Per Capsule',
    'core.collagen': 'Collagen Peptides',
    'core.collagen.dose': '500 mg',
    'core.collagen.desc': 'Deep-sea collagen peptides, light and easily absorbed, helping replenish the "foundation" your skin needs for softness and elasticity.',
    'core.grape': 'Grape Seed Extract',
    'core.grape.dose': '40 mg (Standardized OPC)',
    'core.grape.desc': 'One of nature\'s top antioxidants, gently preserving youthful radiance and reducing daily free radical stress.',
    'ingredient.antioxidant.label': 'DUAL ANTIOXIDANT COMPLEX',
    'ingredient.antioxidant.sublabel': 'For lasting radiance',
    'vit.c': 'Vitamin C',
    'vit.c.dose': '100 mg',
    'vit.c.desc': 'Brightens skin, provides essential antioxidant nutrition, and supports natural collagen synthesis.',
    'vit.e': 'Vitamin E',
    'vit.e.dose': '10 mg α-TE',
    'vit.e.desc': 'Classic fat-soluble antioxidant, works synergistically with Vitamin C to create a protective barrier against oxidation.',
    'vit.beta': 'Beta-Carotene',
    'vit.beta.dose': '500 μg RE',
    'vit.beta.desc': 'A gentler form of Vitamin A, bringing natural radiance to skin and eyes from within.',
    'ingredient.vitb.label': 'B VITAMINS',
    'ingredient.vitb.sublabel': 'Energize and vitalize',
    'vit.b2': 'Vitamin B2',
    'vit.b2.dose': '1.0 mg',
    'vit.b2.desc': 'Participates in energy metabolism, maintaining healthy skin and mucous membranes.',
    'vit.b6': 'Vitamin B6',
    'vit.b6.dose': '1.0 mg',
    'vit.b6.desc': 'Supports protein metabolism, helping the body utilize collagen more effectively.',
    'vit.biotin': 'Biotin',
    'vit.biotin.dose': '80 μg',
    'vit.biotin.desc': 'An essential nutrient for women, helps maintain healthy skin, hair, and nails.',
    'ingredient.sunshine.label': 'SUNSHINE CONFIDENCE',
    'vit.d3': 'Vitamin D3',
    'vit.d3.dose': '10 μg (400 IU)',
    'vit.d3.desc': 'Supplements "sunshine nutrition", supporting skin health and basic body metabolism.',
    'ingredient.mineral.label': 'MINERAL ELEMENTS',
    'ingredient.mineral.sublabel': 'Trace minerals for skin balance',
    'mineral.zinc': 'Zinc',
    'mineral.zinc.dose': '7 mg',
    'mineral.zinc.desc': 'Participates in skin repair and immune maintenance, helping women maintain a more stable state.',
    'mineral.selenium': 'Selenium',
    'mineral.selenium.dose': '30 μg',
    'mineral.selenium.desc': 'Essential antioxidant mineral, works synergistically with grape seed & Vitamin E to preserve youth.',
    'product.footer': 'Every ingredient\'s encounter is a gentle dialogue between nature and science',
    'product.footer.2': 'One capsule, beautiful daily ritual',
    'footer.wish': 'May you always be gentle and be treated gently',
  },
  ko: {
    'seo.title': 'INNEWTOLEA 인뉴톨레아 | 여성 이너뷰티 & 콜라겐 스킨케어 영양제',
    'seo.description': 'INNEWTOLEA 인뉴톨레아 - 여성의 내면의 아름다움을 가꿉니다. 생명의 꽃 포도씨 콜라겐 캡슐은 심해 콜라겐 펩타이드, 포도씨 추출물, 멀티비타민을 결합하여 내면에서 자연스러운 광채를 선사합니다.',
    'seo.keywords': 'INNEWTOLEA,인뉴톨레아,콜라겐,여성미용,이너뷰티,포도씨추출물,스킨케어영양,항산화,뷰티서플리먼트',
    'nav.about': '소개',
    'nav.values': '가치관',
    'nav.ritual': '제품',
    'brand.name': '인뉴톨레아',
    'hero.subtitle': '사랑하는 당신, 저희 고객이든 아니든',
    'hero.title.1': '우리는 믿습니다, 당신은 언제나',
    'hero.title.2': '세상에서 가장 아름다운 여자',
    'hero.desc': '이것은 마케팅 문구가 아닙니다',
    'hero.desc.2': '이것은 브랜드를 설립할 때 처음 품었던 소망입니다',
    'hero.scroll': '스크롤',
    'about.label': '인뉴톨레아 소개',
    'about.title': '인뉴톨레아',
    'about.p1': '우리는 아름다움이 부담이 되어서는 안 된다고 믿습니다',
    'about.p1.2': '오히려 부드러운 일상의 의식이어야 합니다',
    'about.p2': 'INNEWTOLEA는 단순한 소망에서 탄생했습니다:',
    'about.p2.2': '모든 여성이 더 쉽고, 더 부드럽고, 더 지속 가능한 방법으로',
    'about.p2.3': '바쁜 삶 속에서도 자신을 사랑할 수 있도록.',
    'about.p3': '우리는 즉각적인 효과를 추구하지 않습니다',
    'about.p3.2': '우리는 작은 습관의 힘을 믿습니다',
    'about.p3.3': '모든 작은 지속이 조용히 무언가를 바꾸고 있습니다',
    'about.quote': '"자신을 사랑하고, 부드럽게 보살펴 주세요."',
    'values.label': '우리의 가치관',
    'values.title': '우리가 믿는 것',
    'value.1.title': '부드러움은 힘이다',
    'value.1.en': 'Gentleness is Strength',
    'value.1.desc': '진정한 강함은 결코 소리 높일 필요가 없습니다. 자신을 부드럽게 대하는 것이 가장 깊은 용기입니다.',
    'value.2.title': '아름다움은 자유다',
    'value.2.en': 'Beauty is Freedom',
    'value.2.desc': '아름다움에는 정답이 없습니다. 당신의 독특함이 가장 소중한 풍경입니다.',
    'value.3.title': '지속은 가장 로맨틱한 일',
    'value.3.en': 'Persistence is Romance',
    'value.3.desc': '심장 박동처럼 조용하지만, 당신을 빛 속으로 이끌어 줍니다.',
    'value.4.title': '작은 습관도 소중히',
    'value.4.en': 'Small Rituals Matter',
    'value.4.desc': '작은 지속은 당신이 조용히 스스로를 위해 켜는 빛입니다.',
    'value.5.title': '당신은 의식을 누릴 자격이 있다',
    'value.5.en': 'You Deserve Rituals',
    'value.5.desc': '삶의 아름다움은 자신을 진지하게 대하는 순간에 있습니다.',
    'value.6.title': '자기 사랑은 평생의 과제',
    'value.6.en': 'Self-love is Lifelong',
    'value.6.desc': '완벽을 서두를 필요 없습니다. 천천히, 당신은 최고의 자신이 되어가고 있습니다.',
    'women.label': '당신에게',
    'women.title': '이 글을 읽고 있는 모든 당신에게',
    'women.p1': '당신은 세상을 기쁘게 하기 위해 존재하지 않습니다!',
    'women.p1.2': '태양이 당신을 중심으로 빛나게 하세요.',
    'women.p2.1': '어떤 빛은 부드러움에서,',
    'women.p2.2': '어떤 빛은 끈기에서,',
    'women.p2.3': '더 많은 경우, 그것은 간과된 일상 속에 숨어 있습니다.',
    'women.p3.1': '당신은 삶의 가장 진실한 결입니다;',
    'women.p3.2': '그리고 연약함도 허용된 아름다움입니다.',
    'women.p4': '세상을 품는 당신이 부드럽게 대해지길 바라며,',
    'women.p4.2': '그 온기로 자신을 대하길 바랍니다.',
    'ritual.label': 'BEAUTY FROM WITHIN',
    'ritual.title': '스타 제품',
    'product.name': '생명의 꽃',
    'product.name.en': 'Flower of Life',
    'product.desc': '아름다운 변화는 매일 한 알의 부드러움에서 시작됩니다.',
    'ingredient.core.label': '핵심 유효 성분',
    'ingredient.core.sublabel': '1캡슐당 함량',
    'core.collagen': '콜라겐 펩타이드',
    'core.collagen.dose': '500 mg',
    'core.collagen.desc': '심해 콜라겐 펩타이드, 가볍고 흡수가 쉬우며, 피부에 필요한 "기초 원료"를 보충하여 부드러움과 탄력을 되찾게 합니다.',
    'core.grape': '포도씨 추출물',
    'core.grape.dose': '40 mg (표준화 OPC)',
    'core.grape.desc': '자연계 최고의 항산화 성분 중 하나로, 젊은 광채를 부드럽게 지키고 일상의 활성산소 스트레스를 줄여줍니다.',
    'ingredient.antioxidant.label': '이중 항산화 조합',
    'ingredient.antioxidant.sublabel': '지속적인 광채를 위해',
    'vit.c': '비타민 C',
    'vit.c.dose': '100 mg',
    'vit.c.desc': '피부를 환하게 하고, 항산화 기본 영양을 제공하며, 자연스러운 콜라겐 합성을 지원합니다.',
    'vit.e': '비타민 E',
    'vit.e.dose': '10 mg α-TE',
    'vit.e.desc': '클래식한 지용성 항산화제로, 비타민 C와 함께 산화에 대한 보호 장벽을 형성합니다.',
    'vit.beta': '베타카로틴',
    'vit.beta.dose': '500 μg RE',
    'vit.beta.desc': '더 순한 형태의 비타민 A로, 피부와 눈에 자연스러운 광채를 선사합니다.',
    'ingredient.vitb.label': '비타민 B군',
    'ingredient.vitb.sublabel': '에너지와 활력 충전',
    'vit.b2': '비타민 B2',
    'vit.b2.dose': '1.0 mg',
    'vit.b2.desc': '에너지 대사에 참여하여 건강한 피부와 점막을 유지합니다.',
    'vit.b6': '비타민 B6',
    'vit.b6.dose': '1.0 mg',
    'vit.b6.desc': '단백질 대사를 지원하여 콜라겐을 더 효과적으로 활용하도록 돕습니다.',
    'vit.biotin': '비오틴',
    'vit.biotin.dose': '80 μg',
    'vit.biotin.desc': '여성에게 필수적인 영양소로, 건강한 피부, 모발, 손톱 유지를 돕습니다.',
    'ingredient.sunshine.label': '햇살의 자신감',
    'vit.d3': '비타민 D3',
    'vit.d3.dose': '10 μg (400 IU)',
    'vit.d3.desc': '"햇살 영양"을 보충하여 피부 건강과 기초 대사를 지원합니다.',
    'ingredient.mineral.label': '미네랄 원소',
    'ingredient.mineral.sublabel': '피부 균형을 위한 미량 미네랄',
    'mineral.zinc': '아연',
    'mineral.zinc.dose': '7 mg',
    'mineral.zinc.desc': '피부 회복과 면역 유지에 참여하여 더 안정적인 상태를 유지하도록 돕습니다.',
    'mineral.selenium': '셀레늄',
    'mineral.selenium.dose': '30 μg',
    'mineral.selenium.desc': '필수 항산화 미네랄로, 포도씨 & 비타민 E와 함께 젊음을 지킵니다.',
    'product.footer': '모든 성분의 만남은 자연과 과학의 부드러운 대화입니다',
    'product.footer.2': '가벼운 한 알, 아름다운 일상',
    'footer.wish': '언제나 부드럽고, 부드럽게 대해지길',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
