import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'zh' | 'en' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'seo.title': 'INNEWTOLEA 因纽特莱 | 红参燕窝胶原肽饮品 - 生命之花',
    'seo.description': 'INNEWTOLEA因纽特莱，生命之花红参燕窝胶原肽饮品，甄选红参、燕窝、胶原蛋白肽等珍贵原料，每瓶50ml，方便携带，随时享用。温柔呵护，让美丽成为一种日常仪式。',
    'seo.keywords': 'INNEWTOLEA,因纽特莱,红参燕窝,胶原蛋白肽,饮品,生命之花,女性饮品,胶原肽饮料',
    'nav.home': '首页',
    'nav.values': '价值观',
    'nav.brandCulture': '品牌文化',
    'nav.about': '关于',
    'nav.contact': '联系',
    'nav.ritual': '产品',
    'nav.products': '产品',
    'brand.name': '因纽特莱',
    'hero.subtitle': '无论你是否选择 INNEWTOLEA',
    'hero.title.1': '美，依然',
    'hero.title.2': '与你同在',
    'hero.desc': '愿你，始终成为你自己。',
    'hero.desc.2': '',
    'hero.desc.3': '',
    'hero.scroll': '向下滚动',
    'about.label': '品牌文化',
    'about.title': '因纽特莱',
    'about.p1': '我们相信，美不应成为负担，',
    'about.p1.2': '而是一种温柔而持久的日常仪式。',
    'about.p2': 'INNEWTOLEA 诞生于一个简单而坚定的愿望：',
    'about.p2.2': '让女性在忙碌的生活之中，',
    'about.p2.3': '依然能够以更轻松、更温柔、也更可持续的方式，好好地照顾自己。',
    'about.p3': '我们不承诺瞬间的改变。因为真正值得的美，总是在时间里，悄然生长。',
    'about.p3.2': '我们相信小习惯的力量，',
    'about.p3.3': '相信每一次微小而持续的选择，都会在不知不觉中，带来改变。',
    'about.quote': '愿你，始终温柔地对待自己。',
    'values.label': '我们的价值观',
    'values.title': '我们所相信的',
    'value.1.title': '温柔是力量',
    'value.1.en': 'Gentleness is Strength',
    'value.1.desc': '真正的力量，往往安静而坚定。温柔对待自己，本身就是一种勇气。',
    'value.2.title': '美是一种自由',
    'value.2.en': 'Beauty is Freedom',
    'value.2.desc': '美，并不需要被定义。当你成为自己，自由便自然发生。',
    'value.3.title': '坚持是最浪漫的事',
    'value.3.en': 'Persistence is Romance',
    'value.3.desc': '它像心跳一样安静，却在不知不觉中，把你带向光里。',
    'value.4.title': '小习惯值得被珍惜',
    'value.4.en': 'Small Rituals Matter',
    'value.4.desc': '每一个小小的坚持，都是在为自己，留下一点光。',
    'value.5.title': '你值得更好的仪式感',
    'value.5.en': 'You Deserve Rituals',
    'value.5.desc': '生活的质感，往往来自那些被认真对待的时刻。',
    'value.6.title': '爱自己是一生的功课',
    'value.6.en': 'Self-love is Lifelong',
    'value.6.desc': '不必急于成为谁。慢慢来，你正在成为自己。',
    'women.label': '致你的信',
    'women.title': '你好',
    'women.p1': '生命并非为了取悦世界而存在。',
    'women.p2': '真正的光，并不喧哗。它来自温柔，也来自日复一日的坚持，更多时候，藏在那些容易被忽略的小日常里。',
    'women.p3': '脆弱，是生命真实的一部分；被允许的，也同样美。',
    'women.p4': '被温柔对待的感觉，往往从自己开始。',
    'ritual.label': 'BEAUTY FROM WITHIN',
    'ritual.title': '明星产品',
    'product.name': '生命之花 · 小紫瓶',
    'product.name.sub': '燕窝胶原肽饮品',
    'product.name.en': 'Flower of Life',
    'product.spec': '50ml × 10瓶/盒',
    'product.desc': '美好的发生，从每天一次温柔开始。',
    'product.price': '¥618',
    'product.buy': '立即购买',
    'ingredient.core.label': '核心配料',
    'ingredient.core.sublabel': '甄选珍贵原料',
    'core.pqq': 'PQQ',
    'core.pqq.desc': '吡咯喹啉醌，一种存在于多种食物中的天然成分。',
    'core.birdnest': '燕窝肽',
    'core.birdnest.desc': '源自印尼优质燕窝，经酶解工艺制成小分子肽，口感细腻。',
    'core.ejiao': '阿胶肽',
    'core.ejiao.desc': '传统阿胶经现代工艺酶解，更易入口，温润醇厚。',
    'core.ginseng': '红参',
    'core.ginseng.desc': '甄选优质红参，经传统工艺炮制，口感醇厚回甘。',
    'core.rehmannia': '熟地黄',
    'core.rehmannia.desc': '经九蒸九晒传统工艺炮制，色泽乌黑，味道甘甜。',
    'ingredient.other.label': '自然与生命的对话',
    'ingredient.other.sublabel': '来自植物的温柔',
    'other.saffron': '藏红花',
    'other.saffron.subtitle': '来自时间的回应',
    'other.saffron.desc': '源自西班牙的花丝，细腻而克制。它不急于表达，却在每一次相遇中，为风味留下深度。',
    'other.carob': '豆角提取物',
    'other.carob.subtitle': '来自日常的平衡',
    'other.carob.desc': '取自植物本身的清新，口感自然，让味觉回到最简单的状态。不强调存在，却始终在场。',
    'other.pomegranate': '红石榴浓缩汁',
    'other.pomegranate.subtitle': '来自生命的饱满',
    'other.pomegranate.desc': '浓缩的果实精华，酸甜交织。像生命本身，层次丰富，却始终充满活力。',
    'other.rose': '重瓣红玫瑰',
    'other.rose.subtitle': '来自温柔的邀请',
    'other.rose.desc': '生长于高原之上，花香缓慢而悠长。不是为了取悦，而是在靠近时，自然散发。',
    'product.footer': '每一种原料的相遇，都是自然与生命之间，温柔的拥抱。',
    'product.footer.2': '本品为普通食品，非保健食品、非药品，不能替代药物治疗疾病',
    'footer.wish': '让美自然发生',
    'footer.wish.en': 'Let beauty unfold.',
    // Brand Culture Page
    'brandCulture.hero.title': '因纽特莱',
    'brandCulture.hero.subtitle': '我们相信，美丽不应是负担',
    'brandCulture.hero.subtitle2': '而是一种温柔的日常仪式',
    'brandContent.intro': 'INNEWTOLEA 诞生于一个简单的愿望：',
    'brandContent.intro2': '让每一位女性，都能以更轻松、更温柔、更可持续的方式，',
    'brandContent.intro3': '在忙碌的生活中，依然能够好好爱自己。',
    'brandContent.p1': '我们不追求立竿见影的速效',
    'brandContent.p1_2': '我们相信小习惯的力量',
    'brandContent.p1_3': '相信每一个微小的坚持，都在悄悄改变着什么',
    'brandContent.quote': '"请爱上自己，温柔的呵护自己。"',
    // Contact Page
    'contact.hero.title': '联系我们',
    'contact.hero.subtitle': '期待与你相遇',
    'contact.person.label': '品牌合作',
    'contact.person.name': '李浩琦',
    'contact.person.title': '中国区负责人',
    'contact.info.address': '地址',
    'contact.info.address.value': '浙江省杭州市西湖区文三路 90 号',
    'contact.info.phone': '电话',
    'contact.info.phone.value': '+86 1555 6655 009',
    'contact.info.email': '邮箱',
    'contact.info.email.value': 'hello@innewtolea.com',
    'contact.info.wechat': '企业微信',
    'contact.info.wechat.value': 'INNEWTOLEA_Service',
    'contact.info.wechat.scan': '扫码添加企业微信',
    'contact.info.hours': '工作时间',
    'contact.info.hours.value': '周一至周五 9:00 – 18:00',
    // About Page
    'aboutPage.hero.title': 'INNEWTOLEA',
    'aboutPage.hero.subtitle': '因纽特莱',
    'aboutPage.hero.tagline': '进入一段焕新生命的旅程',
    'aboutPage.hero.tagline.en': 'A journey to a renewed, better you',
    'aboutPage.naming.title': '品牌命名寓意',
    'aboutPage.naming.intro': 'INNEWTOLEA 由四个具有象征意义的片段组成：',
    'aboutPage.naming.in.title': 'IN',
    'aboutPage.naming.in.meaning': '进入、由内而生的改变',
    'aboutPage.naming.in.desc': '代表健康从外表开始，但真正的力量源自内在。我们专注身体"内在循环"的改善，用营养支持最根本的改变。',
    'aboutPage.naming.new.title': 'NEW',
    'aboutPage.naming.new.meaning': '新的、更新的、焕新的希望',
    'aboutPage.naming.new.desc': '象征每天的重新开始、重新建立习惯、重新获得能量。也是品牌对用户的承诺："每天一点点，你会发现全新的自己。"',
    'aboutPage.naming.to.title': 'TO',
    'aboutPage.naming.to.meaning': '通往、过程、路径',
    'aboutPage.naming.to.desc': '健康不是一蹴而就，而是一段持续向前的旅程。TO 代表一条让人能够坚持、不造成负担、却真正有效的健康路径。',
    'aboutPage.naming.lea.title': 'LEA',
    'aboutPage.naming.lea.meaning': '生命、生长、活力',
    'aboutPage.naming.lea.desc': '源于柔和音节，象征生命的轻盈、生机与柔韧。让品牌整体更具国际感、美感与生命气息。',
    'aboutPage.philosophy.title': '品牌理念',
    'aboutPage.philosophy.core': '从内而外，走向更好的自己',
    'aboutPage.philosophy.intro': 'INNEWTOLEA 因纽特莱的名字来源于对健康本质的理解：健康不是某一刻的选择，而是一段从内出发、持续更新、朝向更好的生命状态的过程。',
    'aboutPage.philosophy.commitment.title': '我们的承诺',
    'aboutPage.philosophy.commitment.1': '轻奢但不昂贵的体验',
    'aboutPage.philosophy.commitment.2': '科学而不过度营销的配方',
    'aboutPage.philosophy.commitment.3': '人人都能坚持的营养方式',
    'aboutPage.philosophy.commitment.4': '美观、国际化、令人愉悦的产品美学',
    'aboutPage.philosophy.closing': '让每个人，都能以可负担、可坚持的方式，踏上一段属于自己的 INNEWTOLEA 生命焕新旅程。',
    'aboutPage.brand.title': '关于 INNEWTOLEA',
    'aboutPage.brand.intro': 'INNEWTOLEA 因纽特莱，致力于打造以温柔、节律与日常陪伴为核心的女性营养饮品品牌。',
    'aboutPage.brand.formula': '在产品研发过程中，我们持续关注并参考来自韩国、日本等地区的成熟配方理念与原料应用经验，结合东方女性的生活方式与饮用习惯，进行本土化的配方设计与优化。',
    'aboutPage.brand.production': '产品由具备规范食品生产资质的合作工厂完成，在符合食品安全要求的前提下，以稳定的生产流程支持日常品质管理。',
    'aboutPage.brand.logistics': '成品仓储与物流体系设立于安徽亳州，以稳定、可控的方式，支持日常发货与服务需求。',
    'aboutPage.back': '返回首页',
  },
  en: {
    'seo.title': 'INNEWTOLEA | Flower of Life - Red Ginseng Bird\'s Nest Collagen Peptide Drink',
    'seo.description': 'INNEWTOLEA - Flower of Life Red Ginseng Bird\'s Nest Collagen Peptide Drink. Premium ingredients including red ginseng, bird\'s nest, and collagen peptides. 50ml per bottle, convenient and delicious.',
    'seo.keywords': 'INNEWTOLEA,red ginseng,bird nest,collagen peptide,drink,flower of life,collagen drink,beauty drink',
    'nav.home': 'Home',
    'nav.values': 'Values',
    'nav.brandCulture': 'Brand Culture',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.ritual': 'Product',
    'nav.products': 'Products',
    'brand.name': 'INNEWTOLEA',
    'hero.subtitle': 'Whether you choose INNEWTOLEA or not',
    'hero.title.1': 'Beauty remains',
    'hero.title.2': 'With you',
    'hero.desc': 'May you always be yourself.',
    'hero.desc.2': '',
    'hero.desc.3': '',
    'hero.scroll': 'Scroll',
    'about.label': 'ABOUT INNEWTOLEA',
    'about.title': 'INNEWTOLEA',
    'about.p1': 'We believe beauty should not be a burden,',
    'about.p1.2': 'but a gentle and lasting daily ritual.',
    'about.p2': 'INNEWTOLEA was born from a simple yet firm wish:',
    'about.p2.2': 'To help women, even in the midst of busy lives,',
    'about.p2.3': 'take care of themselves in an easier, gentler, and more sustainable way.',
    'about.p3': 'We don\'t promise instant change. Because beauty truly worth having always grows quietly in time.',
    'about.p3.2': 'We believe in the power of small habits,',
    'about.p3.3': 'that every small and consistent choice brings change, without you even noticing.',
    'about.quote': 'May you always treat yourself with tenderness.',
    'values.label': 'OUR VALUES',
    'values.title': 'What We Believe',
    'value.1.title': 'Gentleness is Strength',
    'value.1.en': 'Gentleness is Strength',
    'value.1.desc': 'True strength is often quiet and steady. Treating yourself gently is itself a form of courage.',
    'value.2.title': 'Beauty is Freedom',
    'value.2.en': 'Beauty is Freedom',
    'value.2.desc': 'Beauty doesn\'t need to be defined. When you become yourself, freedom naturally follows.',
    'value.3.title': 'Persistence is Romance',
    'value.3.en': 'Persistence is Romance',
    'value.3.desc': 'It is as quiet as a heartbeat, yet without you noticing, it leads you toward the light.',
    'value.4.title': 'Small Rituals Matter',
    'value.4.en': 'Small Rituals Matter',
    'value.4.desc': 'Every small act of persistence is leaving a little light for yourself.',
    'value.5.title': 'You Deserve Rituals',
    'value.5.en': 'You Deserve Rituals',
    'value.5.desc': 'The texture of life often comes from moments that are treated with care.',
    'value.6.title': 'Self-love is Lifelong',
    'value.6.en': 'Self-love is Lifelong',
    'value.6.desc': 'No need to rush to become someone. Take your time, you are becoming yourself.',
    'women.label': 'A Letter to You',
    'women.title': 'Hello',
    'women.p1': 'Life does not exist to please the world.',
    'women.p2': 'True light is never loud. It comes from gentleness, from day-to-day persistence, and more often, it hides in the small moments easily overlooked.',
    'women.p3': 'Vulnerability is a real part of life; what is allowed is also beautiful.',
    'women.p4': 'The feeling of being treated gently often begins with yourself.',
    'ritual.label': 'BEAUTY FROM WITHIN',
    'ritual.title': 'Star Product',
    'product.name': 'Flower of Life · Little Purple',
    'product.name.sub': 'Bird\'s Nest Collagen Peptide Drink',
    'product.name.en': 'Flower of Life',
    'product.spec': '50ml × 10 bottles/box',
    'product.desc': 'Beautiful changes begin with one gentle bottle each day.',
    'product.price': '$89',
    'product.buy': 'Buy Now',
    'ingredient.core.label': 'KEY INGREDIENTS',
    'ingredient.core.sublabel': 'Premium Selected Ingredients',
    'core.pqq': 'PQQ',
    'core.pqq.desc': 'Pyrroloquinoline quinone, a natural compound found in various foods.',
    'core.birdnest': 'Bird\'s Nest Peptide',
    'core.birdnest.desc': 'From premium Indonesian bird\'s nest, enzymatically processed into small peptides, smooth texture.',
    'core.ejiao': 'Ejiao Peptide',
    'core.ejiao.desc': 'Traditional donkey-hide gelatin processed with modern enzymatic technology, smooth and mellow.',
    'core.ginseng': 'Red Ginseng',
    'core.ginseng.desc': 'Selected premium red ginseng, traditionally processed, rich taste with sweet aftertaste.',
    'core.rehmannia': 'Rehmannia',
    'core.rehmannia.desc': 'Processed through traditional nine-steam nine-sun method, dark color with sweet taste.',
    'ingredient.other.label': 'A Dialogue Between Nature and Life',
    'ingredient.other.sublabel': 'Gentleness from plants',
    'other.saffron': 'Saffron',
    'other.saffron.subtitle': 'A response from time',
    'other.saffron.desc': 'Delicate threads from Spain, subtle yet refined. It doesn\'t rush to express, yet leaves depth in every encounter.',
    'other.carob': 'Carob Extract',
    'other.carob.subtitle': 'Balance from the everyday',
    'other.carob.desc': 'Fresh essence from the plant itself, naturally clean, returning taste to its simplest state. Never demanding attention, yet always present.',
    'other.pomegranate': 'Pomegranate Concentrate',
    'other.pomegranate.subtitle': 'Fullness from life',
    'other.pomegranate.desc': 'Concentrated fruit essence, sweet and tangy intertwined. Like life itself, richly layered, yet always vibrant.',
    'other.rose': 'Damask Rose',
    'other.rose.subtitle': 'An invitation from gentleness',
    'other.rose.desc': 'Grown on highland heights, its fragrance slow and lingering. Not to please, but to naturally unfold when you draw near.',
    'product.footer': 'Every ingredient\'s encounter is a gentle embrace between nature and life.',
    'product.footer.2': 'One bottle daily, gentle ritual',
    'footer.wish': 'Let Beauty Unfold',
    'footer.wish.en': 'Let beauty unfold.',
    // Brand Culture Page
    'brandCulture.hero.title': 'INNEWTOLEA',
    'brandCulture.hero.subtitle': 'We believe beauty should not be a burden',
    'brandCulture.hero.subtitle2': 'But a gentle daily ritual',
    'brandContent.intro': 'INNEWTOLEA was born from a simple wish:',
    'brandContent.intro2': 'To help every woman love herself',
    'brandContent.intro3': 'in an easier, gentler, more sustainable way, even in a busy life.',
    'brandContent.p1': 'We don\'t pursue instant results',
    'brandContent.p1_2': 'We believe in the power of small habits',
    'brandContent.p1_3': 'Every tiny persistence is quietly changing something',
    'brandContent.quote': '"Please fall in love with yourself, and care for yourself tenderly."',
    // Contact Page
    'contact.hero.title': 'Contact',
    'contact.hero.subtitle': 'We look forward to meeting you',
    'contact.person.label': 'Partnership',
    'contact.person.name': 'Haoqi Li',
    'contact.person.title': 'China Director',
    'contact.info.address': 'Address',
    'contact.info.address.value': 'No. 90 Wensan Road, Xihu District, Hangzhou, Zhejiang',
    'contact.info.phone': 'Phone',
    'contact.info.phone.value': '+86 1555 6655 009',
    'contact.info.email': 'Email',
    'contact.info.email.value': 'hello@innewtolea.com',
    'contact.info.wechat': 'WeChat',
    'contact.info.wechat.value': 'INNEWTOLEA_Service',
    'contact.info.wechat.scan': 'Scan to connect',
    'contact.info.hours': 'Hours',
    'contact.info.hours.value': 'Mon – Fri 9:00 – 18:00',
    // About Page
    'aboutPage.hero.title': 'INNEWTOLEA',
    'aboutPage.hero.subtitle': 'INNEWTOLEA',
    'aboutPage.hero.tagline': 'A journey to a renewed, better you',
    'aboutPage.hero.tagline.en': 'A journey to a renewed, better you',
    'aboutPage.naming.title': 'Brand Name Meaning',
    'aboutPage.naming.intro': 'INNEWTOLEA is composed of four symbolic fragments:',
    'aboutPage.naming.in.title': 'IN',
    'aboutPage.naming.in.meaning': 'Inner transformation',
    'aboutPage.naming.in.desc': 'Health starts from the outside, but true strength comes from within. We focus on improving the body\'s "inner cycle" with nutritional support for fundamental change.',
    'aboutPage.naming.new.title': 'NEW',
    'aboutPage.naming.new.meaning': 'New beginnings, renewal, hope',
    'aboutPage.naming.new.desc': 'Symbolizes daily fresh starts, rebuilding habits, regaining energy. Our promise to you: "Little by little, you\'ll discover a brand new you."',
    'aboutPage.naming.to.title': 'TO',
    'aboutPage.naming.to.meaning': 'Toward, journey, pathway',
    'aboutPage.naming.to.desc': 'Health isn\'t achieved overnight—it\'s a continuous journey forward. TO represents a sustainable, burden-free, yet truly effective path to wellness.',
    'aboutPage.naming.lea.title': 'LEA',
    'aboutPage.naming.lea.meaning': 'Life, growth, vitality',
    'aboutPage.naming.lea.desc': 'Derived from soft syllables, symbolizing life\'s lightness, vitality, and resilience. Giving the brand an international, aesthetic, and life-affirming presence.',
    'aboutPage.philosophy.title': 'Brand Philosophy',
    'aboutPage.philosophy.core': 'From within to without, toward a better you',
    'aboutPage.philosophy.intro': 'The name INNEWTOLEA comes from understanding the essence of health: it\'s not a single choice, but a journey from within, continuously renewing toward a better state of being.',
    'aboutPage.philosophy.commitment.title': 'Our Commitment',
    'aboutPage.philosophy.commitment.1': 'Affordable luxury experience',
    'aboutPage.philosophy.commitment.2': 'Science-based, not over-marketed formulas',
    'aboutPage.philosophy.commitment.3': 'Nutrition everyone can sustain',
    'aboutPage.philosophy.commitment.4': 'Beautiful, international, delightful product aesthetics',
    'aboutPage.philosophy.closing': 'Enabling everyone to embark on their own INNEWTOLEA journey of life renewal in an affordable, sustainable way.',
    'aboutPage.brand.title': 'About INNEWTOLEA',
    'aboutPage.brand.intro': 'INNEWTOLEA is dedicated to creating a women\'s nutritional beverage brand centered on gentleness, rhythm, and daily companionship.',
    'aboutPage.brand.formula': 'In our product development, we continuously study and reference mature formulation concepts and ingredient applications from regions like Korea and Japan, combining them with the lifestyles and drinking habits of Asian women to create localized formula designs and optimizations.',
    'aboutPage.brand.production': 'Our products are manufactured by partner factories with proper food production qualifications, ensuring food safety compliance while maintaining stable production processes for daily quality management.',
    'aboutPage.brand.logistics': 'Our finished product warehousing and logistics system is established in Bozhou, Anhui, supporting daily shipping and service needs in a stable and controlled manner.',
    'aboutPage.back': 'Back to Home',
  },
  ko: {
    'seo.title': 'INNEWTOLEA 인뉴톨레아 | 생명의 꽃 - 홍삼 제비집 콜라겐 펩타이드 음료',
    'seo.description': 'INNEWTOLEA 인뉴톨레아 - 생명의 꽃 홍삼 제비집 콜라겐 펩타이드 음료. 홍삼, 제비집, 콜라겐 펩타이드 등 프리미엄 원료를 엄선. 병당 50ml, 휴대하기 편리하고 맛있습니다.',
    'seo.keywords': 'INNEWTOLEA,인뉴톨레아,홍삼,제비집,콜라겐펩타이드,음료,생명의꽃,콜라겐음료',
    'nav.home': '홈',
    'nav.values': '가치관',
    'nav.brandCulture': '브랜드 문화',
    'nav.about': '소개',
    'nav.contact': '연락처',
    'nav.ritual': '제품',
    'nav.products': '제품',
    'brand.name': '인뉴톨레아',
    'hero.subtitle': 'INNEWTOLEA를 선택하든 안 하든',
    'hero.title.1': '아름다움은 여전히',
    'hero.title.2': '당신과 함께',
    'hero.desc': '언제나 당신 자신으로 있기를.',
    'hero.desc.2': '',
    'hero.desc.3': '',
    'hero.scroll': '스크롤',
    'about.label': '인뉴톨레아 소개',
    'about.title': '인뉴톨레아',
    'about.p1': '우리는 아름다움이 부담이 되어서는 안 된다고 믿습니다,',
    'about.p1.2': '오히려 부드럽고 지속적인 일상의 의식이어야 합니다.',
    'about.p2': 'INNEWTOLEA는 단순하지만 확고한 소망에서 탄생했습니다:',
    'about.p2.2': '바쁜 삶 속에서도 여성들이',
    'about.p2.3': '더 쉽고, 더 부드럽고, 더 지속 가능한 방식으로 자신을 돌볼 수 있도록.',
    'about.p3': '우리는 순간적인 변화를 약속하지 않습니다. 진정으로 가치 있는 아름다움은 언제나 시간 속에서 조용히 자라기 때문입니다.',
    'about.p3.2': '우리는 작은 습관의 힘을 믿습니다,',
    'about.p3.3': '작고 꾸준한 선택 하나하나가 어느새 변화를 가져온다고 믿습니다.',
    'about.quote': '언제나 자신을 부드럽게 대하시길.',
    'values.label': '우리의 가치관',
    'values.title': '우리가 믿는 것',
    'value.1.title': '부드러움은 힘이다',
    'value.1.en': 'Gentleness is Strength',
    'value.1.desc': '진정한 힘은 종종 조용하고 단단합니다. 자신을 부드럽게 대하는 것, 그 자체가 용기입니다.',
    'value.2.title': '아름다움은 자유다',
    'value.2.en': 'Beauty is Freedom',
    'value.2.desc': '아름다움은 정의될 필요가 없습니다. 당신이 자신이 될 때, 자유는 자연스럽게 찾아옵니다.',
    'value.3.title': '지속은 가장 로맨틱한 일',
    'value.3.en': 'Persistence is Romance',
    'value.3.desc': '심장 박동처럼 조용하지만, 어느새 당신을 빛 속으로 이끌어 줍니다.',
    'value.4.title': '작은 습관도 소중히',
    'value.4.en': 'Small Rituals Matter',
    'value.4.desc': '작은 지속 하나하나가 자신을 위해 남기는 빛입니다.',
    'value.5.title': '당신은 의식을 누릴 자격이 있다',
    'value.5.en': 'You Deserve Rituals',
    'value.5.desc': '삶의 질감은 종종 정성껏 대하는 순간에서 옵니다.',
    'value.6.title': '자기 사랑은 평생의 과제',
    'value.6.en': 'Self-love is Lifelong',
    'value.6.desc': '누군가가 되려고 서두를 필요 없습니다. 천천히, 당신은 자신이 되어가고 있습니다.',
    'women.label': '당신에게 보내는 편지',
    'women.title': '안녕하세요',
    'women.p1': '생명은 세상을 기쁘게 하기 위해 존재하지 않습니다.',
    'women.p2': '진정한 빛은 결코 시끄럽지 않습니다. 그것은 부드러움에서, 매일의 꾸준함에서 오며, 더 많은 경우, 쉽게 간과되는 작은 일상 속에 숨어 있습니다.',
    'women.p3': '연약함은 삶의 진실한 일부입니다; 허용된 것 또한 아름답습니다.',
    'women.p4': '부드럽게 대해지는 느낌은 종종 자신에게서 시작됩니다.',
    'ritual.label': 'BEAUTY FROM WITHIN',
    'ritual.title': '스타 제품',
    'product.name': '생명의 꽃 · 리틀 퍼플',
    'product.name.sub': '제비집 콜라겐 펩타이드 음료',
    'product.name.en': 'Flower of Life',
    'product.spec': '50ml × 10병/박스',
    'product.desc': '아름다운 변화는 매일 한 병의 부드러움에서 시작됩니다.',
    'product.price': '₩120,000',
    'product.buy': '구매하기',
    'ingredient.core.label': '핵심 원료',
    'ingredient.core.sublabel': '엄선된 프리미엄 원료',
    'core.pqq': 'PQQ',
    'core.pqq.desc': '피롤로퀴놀린 퀴논, 다양한 식품에서 발견되는 천연 성분.',
    'core.birdnest': '제비집 펩타이드',
    'core.birdnest.desc': '인도네시아산 프리미엄 제비집을 효소 분해하여 작은 펩타이드로 가공, 부드러운 질감.',
    'core.ejiao': '아교 펩타이드',
    'core.ejiao.desc': '전통 아교를 현대 효소 기술로 가공, 부드럽고 깊은 맛.',
    'core.ginseng': '홍삼',
    'core.ginseng.desc': '엄선된 프리미엄 홍삼, 전통 공법으로 가공, 깊은 맛과 달콤한 여운.',
    'core.rehmannia': '숙지황',
    'core.rehmannia.desc': '전통 구증구포 공법으로 가공, 검은 색상과 달콤한 맛.',
    'ingredient.other.label': '자연과 생명의 대화',
    'ingredient.other.sublabel': '식물의 부드러움',
    'other.saffron': '사프란',
    'other.saffron.subtitle': '시간의 응답',
    'other.saffron.desc': '스페인산 섬세한 꽃술, 절제되고 정교합니다. 서두르지 않지만, 매 만남에서 깊이를 남깁니다.',
    'other.carob': '캐롭 추출물',
    'other.carob.subtitle': '일상의 균형',
    'other.carob.desc': '식물 본연의 신선함, 자연스럽고 깔끔하게 미각을 가장 단순한 상태로 되돌립니다. 존재를 강조하지 않지만, 항상 함께합니다.',
    'other.pomegranate': '석류 농축액',
    'other.pomegranate.subtitle': '생명의 충만함',
    'other.pomegranate.desc': '농축된 과일 에센스, 새콤달콤이 어우러집니다. 생명 그 자체처럼, 풍부한 층위를 가지면서도 항상 활력이 넘칩니다.',
    'other.rose': '다마스크 장미',
    'other.rose.subtitle': '부드러움의 초대',
    'other.rose.desc': '고원에서 자란, 향기가 느리고 길게 퍼집니다. 기쁘게 하려는 것이 아니라, 가까이 다가갈 때 자연스럽게 피어납니다.',
    'product.footer': '모든 원료의 만남은 자연과 생명 사이의 부드러운 포옹입니다.',
    'product.footer.2': '매일 한 병, 부드러운 일상',
    'footer.wish': '아름다움이 자연스럽게',
    'footer.wish.en': 'Let beauty unfold.',
    // Brand Culture Page
    'brandCulture.hero.title': '인뉴톨레아',
    'brandCulture.hero.subtitle': '우리는 아름다움이 부담이 되어서는 안 된다고 믿습니다',
    'brandCulture.hero.subtitle2': '오히려 부드러운 일상의 의식이어야 합니다',
    'brandContent.intro': 'INNEWTOLEA는 단순한 소망에서 탄생했습니다:',
    'brandContent.intro2': '모든 여성이 더 쉽고, 더 부드럽고, 더 지속 가능한 방법으로',
    'brandContent.intro3': '바쁜 삶 속에서도 자신을 사랑할 수 있도록.',
    'brandContent.p1': '우리는 즉각적인 효과를 추구하지 않습니다',
    'brandContent.p1_2': '우리는 작은 습관의 힘을 믿습니다',
    'brandContent.p1_3': '모든 작은 지속이 조용히 무언가를 바꾸고 있습니다',
    'brandContent.quote': '"자신을 사랑하고, 부드럽게 보살펴 주세요."',
    // Contact Page
    'contact.hero.title': '연락처',
    'contact.hero.subtitle': '만나기를 기대합니다',
    'contact.person.label': '파트너십',
    'contact.person.name': '이호기',
    'contact.person.title': '중국 지역 책임자',
    'contact.info.address': '주소',
    'contact.info.address.value': '저장성 항저우시 서호구 문산로 90호',
    'contact.info.phone': '전화',
    'contact.info.phone.value': '+86 1555 6655 009',
    'contact.info.email': '이메일',
    'contact.info.email.value': 'hello@innewtolea.com',
    'contact.info.wechat': '위챗',
    'contact.info.wechat.value': 'INNEWTOLEA_Service',
    'contact.info.wechat.scan': '스캔하여 연결',
    'contact.info.hours': '업무 시간',
    'contact.info.hours.value': '월–금 9:00 – 18:00',
    // About Page
    'aboutPage.hero.title': 'INNEWTOLEA',
    'aboutPage.hero.subtitle': '인뉴톨레아',
    'aboutPage.hero.tagline': '새로운 삶의 여정으로',
    'aboutPage.hero.tagline.en': 'A journey to a renewed, better you',
    'aboutPage.naming.title': '브랜드 네이밍 의미',
    'aboutPage.naming.intro': 'INNEWTOLEA는 네 가지 상징적인 조각으로 구성됩니다:',
    'aboutPage.naming.in.title': 'IN',
    'aboutPage.naming.in.meaning': '내면의 변화',
    'aboutPage.naming.in.desc': '건강은 외면에서 시작되지만, 진정한 힘은 내면에서 옵니다. 우리는 근본적인 변화를 위한 영양 지원으로 신체의 "내부 순환" 개선에 집중합니다.',
    'aboutPage.naming.new.title': 'NEW',
    'aboutPage.naming.new.meaning': '새로운 시작, 갱신, 희망',
    'aboutPage.naming.new.desc': '매일의 새로운 시작, 습관 재건, 에너지 회복을 상징합니다. 당신에게 드리는 약속: "조금씩, 완전히 새로운 자신을 발견하게 될 것입니다."',
    'aboutPage.naming.to.title': 'TO',
    'aboutPage.naming.to.meaning': '향하여, 여정, 경로',
    'aboutPage.naming.to.desc': '건강은 하룻밤에 이루어지지 않습니다—지속적인 전진의 여정입니다. TO는 지속 가능하고, 부담 없으며, 진정으로 효과적인 웰니스 경로를 나타냅니다.',
    'aboutPage.naming.lea.title': 'LEA',
    'aboutPage.naming.lea.meaning': '생명, 성장, 활력',
    'aboutPage.naming.lea.desc': '부드러운 음절에서 유래하여 삶의 가벼움, 활력, 회복력을 상징합니다. 브랜드에 국제적이고 미학적이며 생명력 있는 존재감을 부여합니다.',
    'aboutPage.philosophy.title': '브랜드 철학',
    'aboutPage.philosophy.core': '내면에서 외면으로, 더 나은 자신을 향해',
    'aboutPage.philosophy.intro': 'INNEWTOLEA라는 이름은 건강의 본질에 대한 이해에서 비롯됩니다: 건강은 단일한 선택이 아니라, 내면에서 시작하여 지속적으로 갱신하며 더 나은 존재 상태를 향한 여정입니다.',
    'aboutPage.philosophy.commitment.title': '우리의 약속',
    'aboutPage.philosophy.commitment.1': '합리적인 럭셔리 경험',
    'aboutPage.philosophy.commitment.2': '과학 기반, 과대 마케팅 없는 포뮬러',
    'aboutPage.philosophy.commitment.3': '누구나 지속할 수 있는 영양',
    'aboutPage.philosophy.commitment.4': '아름답고 국제적이며 즐거운 제품 미학',
    'aboutPage.philosophy.closing': '모든 사람이 합리적이고 지속 가능한 방식으로 자신만의 INNEWTOLEA 생명 갱신 여정을 시작할 수 있도록 합니다.',
    'aboutPage.brand.title': 'INNEWTOLEA 소개',
    'aboutPage.brand.intro': 'INNEWTOLEA 인뉴톨레아는 부드러움, 리듬, 일상의 동반을 핵심으로 하는 여성 영양 음료 브랜드를 만들기 위해 노력하고 있습니다.',
    'aboutPage.brand.formula': '제품 개발 과정에서 한국, 일본 등 지역의 성숙한 배합 개념과 원료 응용 경험을 지속적으로 연구하고 참고하며, 동양 여성의 생활 방식과 음용 습관을 결합하여 현지화된 배합 설계와 최적화를 진행합니다.',
    'aboutPage.brand.production': '제품은 규범적인 식품 생산 자격을 갖춘 협력 공장에서 완성되며, 식품 안전 요구 사항을 준수하는 전제 하에 안정적인 생산 프로세스로 일상적인 품질 관리를 지원합니다.',
    'aboutPage.brand.logistics': '완제품 창고 및 물류 시스템은 안후이성 보저우에 설립되어 안정적이고 통제된 방식으로 일상적인 배송 및 서비스 요구를 지원합니다.',
    'aboutPage.back': '홈으로 돌아가기',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string): string => {
    const value = translations[language][key];
    return value !== undefined ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
